[package]
name = "gluesql"
version = "0.1.0"
authors = ["Taehoon Moon <panarch@kaist.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.27"
bincode = "1.2.1"
boolinator = "2.4.0"
nom-sql = "0.0.11"
serde = { version = "1.0.104", features = ["derive"] }
sled = "0.31.0"
thiserror = "1.0.12"
