[package]
name = "gluesql"
version = "0.1.8"
authors = ["Taehoon Moon <panarch@kaist.ac.kr>"]
edition = "2018"
description = "GlueSQL - Open source SQL database engine fully written in Rust with pure functional execution layer, easily swappable storage and web assembly support!"
license = "MPL-2.0"
repository = "https://github.com/gluesql/gluesql"

[features]
sled-storage = ["sled", "bincode"]

[dependencies]
boolinator = "2.4.0"
im-rc = "15.0.0"
iter-enum = "0.2"
or-iterator = "0.1.1"
serde = { version = "1.0.104", features = ["derive"] }
sqlparser = { version = "0.6.1", features = ["serde"] }
thiserror = "1.0.12"

# dependencies for sled-storage
bincode = { version = "1.3.1", optional = true }
sled = { version = "0.34.2", optional = true }
